/**
 * this file is generated by butterfly.js optimizer
 */
 //debug时，由view自己加载绑定
 //运行时，通过打包实现
 define(['butterfly/page', 'text!mail/index.html', 'mail/index'], 
 	function(Page, html, v1){

 	return new PageView(html);
 });